server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    name: test
    url: jdbc:mysql://106.14.184.56:3306/mango_meb?characterEncoding=utf-8
    username: root
    password: Bai880806
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    mode: HTML5
   # suffix: .html
   # encoding: UTF-8
   # content-type: text/html
    cache: false
    prefix: classpath:/templates/
#email配置
  mail:
    host: smtp.qq.com
    username: 346232774@qq.com
    password: keptxddrxmcfbjga
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#freemarker
  freemarker:
    template-loader-path: classpath:/static/template/
    enabled: true
    cache: false
    charset: UTF-8
    content-type: text/html
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-spring-macro-helpers: false
    expose-session-attributes: false
    #jpa 自动生成数据表单
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mango.model
securityconfig:
  logoutsuccessurl: /
  permitall: /rest/**,/bbs**
  deniedpage: /deny
  urlroles: /**/new = manage,admin;
             /**/edit/** = admin;
             /**/delete/** = admin;
